[package]
name = "sortedvec"
version = "0.1.0"
authors = ["Marcus Klaas <mail@marcusklaas.nl>"]
edition = "2018"
description = " a rust vector that enables quick lookups "
license = "Apache-2.0"
repository = "https://github.com/marcusklaas/sortedvec"
keywords = [ "sortedvec", "lookup" ]
readme = "readme.md"

[dependencies]
